### ISSUE TITLE
Could you provide a multi-node execution example?

### ISSUE THREAD

**Issue by Iacob-Alexandru-Andrei** [microsoft/msrflute#17]
Hello,
My research group at the University of Cambridge is looking to benchmark Flute on a multi-node setup using our machine cluster.
We have been unable to find an example script for launching multi-node executions, could you please provide it for us?

**Comment by Mirian-Hipolito** [comment]
Hi @Iacob-Alexandru-Andrei, thanks for opening this issue. 

The latest version of FLUTE is presenting some issues for multi-node jobs, we are currently working on this. You can expect a reply in the incoming few weeks, we apologize for this inconvenience.  😕

Thanks,
Mirian.

**Comment by Iacob-Alexandru-Andrei** [comment]
Thank you very much, do keep us updated.

Best, 
Alex

**Comment by Mirian-Hipolito** [comment]
Hi @Iacob-Alexandru-Andrei,

We have fixed the multi-node setup in FLUTE in our latest PR. Following the example provided in the README, in order to launch the nlg_gru task using a multi-node configuration you only need to add the `--nnodes` parameter to the launching line, indicating your available nodes.

In the example below, we are using 2 nodes with 4 GPUs each when running NCCL backend:

`python -m torch.distributed.run --nnodes=2 --nproc_per_node=4 e2e_trainer.py -dataPath ./testing -outputPath scratch -config testing/hello_world_nlg_gru.yaml -task nlg_gru -backend nccl`

Let us know if you have any question.

Thanks,
Mirian.
