### ISSUE TITLE
FLUTE GPU utilisation vs performance

### ISSUE THREAD

**Issue by Iacob-Alexandru-Andrei** [microsoft/msrflute#18]
Hello,

While running a series of benchmarks between FLUTE and other frameworks we have observed a consistently high degree of GPU compute utilisation with low memory utilisation on the part of FLUTE. The backend used was NCCL.

Despite outclassing the other frameworks in compute utilisation, FLUTE underperforms in terms of round duration compared to one of the others by a factor of 2-4x. All experiments were carried out using the same hardware resource with either 2 or 4 GPUs and our results hold for both fast aggregation and normal aggregation.

Could you highlight some potential bottlenecks that FLUTE may encounter in an image task such that the high GPU utilisation does not translate to lower round duration? 

We are interested in providing a fair comparison and would like some pointers for potential issues that may suppress the performance of FLUTE.

**Comment by simra** [comment]
Glad to hear you are running some benchmarks- we'll look forward to hearing about your results.

Over the fall we invested a lot of effort into improving the GPU utilization, and we saw about 30% performance gains in the per-round duration.  However we haven't recently investigated any outstanding bottlenecks or how to address them.

One thing that might provide some clues is to enable profiling in the server or client. Both server and client configurations have a do_profiling option which will enable the python profiler and also compute some durations of interest and log them as metrics.  I would start with only enabling this in the server since profiling in the client can become very chatty.  Let us know if you need any more details and we can walk you through through setting up the config and interpreting the results.

**Comment by Iacob-Alexandru-Andrei** [comment]
Thank you very much for your quick reply, I will make sure to contact you if we need further information following the profiling.
